"""add waste category and priority

Revision ID: 7de530a11c1f
Revises: 56bc06dd8299
Create Date: 2026-06-15 12:41:11.916363

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7de530a11c1f'
down_revision: Union[str, Sequence[str], None] = '56bc06dd8299'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('ai_results',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('complaint_id', sa.Integer(), nullable=True),
    sa.Column('user_category', sa.String(), nullable=True),
    sa.Column('ai_category', sa.String(), nullable=True),
    sa.Column('confidence', sa.Float(), nullable=True),
    sa.Column('severity_score', sa.Float(), nullable=True),
    sa.Column('priority', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['complaint_id'], ['complaints.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.add_column('complaints', sa.Column('waste_category', sa.String(), nullable=True))
    op.add_column('complaints', sa.Column('priority', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('complaints', 'priority')
    op.drop_column('complaints', 'waste_category')
    op.drop_table('ai_results')
    # ### end Alembic commands ###
