"""add forecasts table

Revision ID: 96b0a270ba64
Revises: d28fa6c70593
Create Date: 2026-06-15 13:53:02.072897

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '96b0a270ba64'
down_revision: Union[str, Sequence[str], None] = 'd28fa6c70593'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('forecasts',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('latitude', sa.Float(), nullable=True),
    sa.Column('longitude', sa.Float(), nullable=True),
    sa.Column('current_complaints', sa.Integer(), nullable=True),
    sa.Column('predicted_complaints', sa.Integer(), nullable=True),
    sa.Column('predicted_risk', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('forecasts')
    # ### end Alembic commands ###
