"""add hotspots table

Revision ID: d28fa6c70593
Revises: 4b078f449aae
Create Date: 2026-06-15 13:04:10.631257

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd28fa6c70593'
down_revision: Union[str, Sequence[str], None] = '4b078f449aae'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('hotspots',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('latitude', sa.Float(), nullable=True),
    sa.Column('longitude', sa.Float(), nullable=True),
    sa.Column('complaint_count', sa.Integer(), nullable=True),
    sa.Column('average_severity', sa.Float(), nullable=True),
    sa.Column('risk_level', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('hotspots')
    # ### end Alembic commands ###
